import jax
import jax.numpy as jnp
import pandas as pd
import numpyro
from numpyro.infer import MCMC, NUTS, init_to_median
import arviz as az
from pathlib import Path
from lung_cancer_spatial.models.car_v4_7 import car_model_v4_7

def run_v4_7_quick_check():
    BASE_DIR = Path("/Users/alydiaowens/Projects/uk-lung-cancer-spatial")
    
    # Ensure you are loading the CSV generated by your fixed build_inputs_V4.py
    df = pd.read_csv(BASE_DIR / "data/processed/inputs_v4_stratified.csv")
    
    y = jnp.array(df['Lung_Cancer'].values)
    E = jnp.array(df['All_Causes'].values)
    bsmokecentered = jnp.array(df['bsmokecentered'].values)
    bmen = jnp.array(df['bmen'].values)

    # V4.7 STABILIZATION SETTINGS:
    # 1. target_accept_prob=0.99 forces smaller, more precise steps.
    # 2. dense_mass=True helps the sampler navigate the now-'pinned' geometry.
    nuts_kernel = NUTS(
        car_model_v4_7, 
        target_accept_prob=0.95, 
        dense_mass=True,
        init_strategy=init_to_median
    )

    # QUICK CHECK CONFIG: 1000 Warmup / 500 Samples
    mcmc = MCMC(
        nuts_kernel, 
        num_warmup=2000, 
        num_samples=2000, 
        num_chains=4
    )
    
    print("🚀 Launching V4.7 Quick Check (Pinned Intercept / 0.95 Target)...")
    mcmc.run(
        jax.random.PRNGKey(42), 
        y=y, 
        E=E, 
        bsmokecentered=bsmokecentered, 
        bmen=bmen
    )
    
    idata = az.from_numpyro(mcmc)
    output_path = BASE_DIR / "outputs/idata_car_v4.7_check.nc"
    idata.to_netcdf(output_path)
    
    # Instant Terminal Feedback on R-hat
    summary = az.summary(idata, var_names=["b0", "sigma", "beta_smoke"])
    print("\n📊 --- QUICK CHECK DIAGNOSTICS ---")
    print(summary[['mean', 'r_hat']])
    print(f"\n✅ Quick check complete. Data saved to: {output_path}")

if __name__ == "__main__":
    run_v4_7_quick_check()